# List available commands
default:
    just --list --unsorted

# Set up dev container. This step runs after building the dev container
post-create: take-ownership-of-module-volumes setup-zsh-environment install-atuin

[private]
take-ownership-of-module-volumes:
    #!/bin/zsh

    sudo chown -R node:node \
      /workspaces/jest-to-vitest-codemod/node_modules \
      /workspaces/jest-to-vitest-codemod/example/node_modules

[private]
setup-zsh-environment:
    #!/bin/zsh

    echo "Updating zsh configuration"
    cp -f .zshrc ~/.zshrc

[private]
install-atuin:
    #!/bin/zsh

    echo Y | bash <(curl --proto '=https' --tlsv1.2 -sSf https://setup.atuin.sh)
